$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: "0.2"
enabledLanguageIds:
  - coq
languageSettings:
  - languageId: "*"
    locale: "*"
    caseSensitive: false
ignorePaths:
  - "*Test.v"
words:
  - andb
  - decr
  - elim
  - fixpoint
  - fixpoints
  - forall
  - involutive
  - minustwo
  - mult
  - nandb
  - nbeq
  - negb
  - nullary
